# ---------------------------------------------------------------------------- #
## \file Dockerfile.armhf
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
ARG tag=debian:13
FROM $tag

RUN export DEBIAN_FRONTEND=noninteractive\
 && dpkg --add-architecture armhf\
 && apt-get -y update\
 && apt-get -y install --no-install-recommends\
    apt-utils\
    build-essential\
    chrpath\
    cmake\
    debhelper\
    dh-make\
    dose-distcheck\
    dpkg-cross\
    fakeroot\
    g++-arm-linux-gnueabihf\
    help2man\
    liblirc-dev:armhf\
    libmpdclient-dev:armhf\
    lintian\
    pkg-config
