# ---------------------------------------------------------------------------- #
## \file Dockerfile.arm64
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
ARG tag=debian:13
FROM $tag

RUN export DEBIAN_FRONTEND=noninteractive\
 && dpkg --add-architecture arm64\
 && apt-get -y update\
 && apt-get -y install --no-install-recommends\
    apt-utils\
    build-essential\
    chrpath\
    cmake\
    debhelper\
    dh-make\
    dose-distcheck\
    dpkg-cross\
    fakeroot\
    g++-aarch64-linux-gnu\
    help2man\
    liblirc-dev:arm64\
    libmpdclient-dev:arm64\
    lintian\
    pkg-config
